_wandb:
    value:
        cli_version: 0.25.0
        e:
            f029t7d1hxv6dwydcbw21l32d1upjvb8:
                args:
                    - --model_dir=../../../pretrained_models/CosyVoice2-0.5B
                    - --llm_checkpoint=exp/cosyvoice2/llm_lr1e-6_batch8000/epoch_9_whole.pt
                    - --prompt_audio=../../../data/qinche/inference_ref/prompt_1.wav
                    - --prompt_text=跟你做的每一件事，都不讨厌。
                    - --text_file=inference_texts.txt
                    - --output_dir=exp/cosyvoice2/llm_lr1e-6_batch8000/inference_epoch_9_last
                    - --use_wandb
                    - --wandb_project=cosyvoice-qinche-clean
                    - --wandb_run_id=llm-ft-20260305-120912
                    - --wandb_run_name=llm-finetune-lr-batch-20260305-120912_epoch9_last_prompt1
                codePath: examples/qinche/cosyvoice2/inference.py
                codePathLocal: inference.py
                cpu_count: 96
                cpu_count_logical: 192
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "3719290880000"
                        used: "479108329472"
                email: haoranzhang.me@gmail.com
                executable: /data_hss/miniconda3/envs/cosyvoice/bin/python
                git:
                    commit: 04bcadc6340e266b4ba09f4474b4668c444aa063
                    remote: https://github.com/FunAudioLLM/CosyVoice.git
                gpu: NVIDIA H200
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Hopper
                      cudaCores: 16896
                      memoryTotal: "150754820096"
                      name: NVIDIA H200
                      uuid: GPU-b8d6b160-0e27-5d0a-787e-da688b2b1a64
                host: nb-6819e6860e28a04e0f-76cc799cdc-9f6zs
                memory:
                    total: "2164153065472"
                os: Linux-5.15.0-140-generic-x86_64-with-glibc2.36
                program: /data_hss/zhanghaoran/CosyVoice/examples/qinche/cosyvoice2/inference.py
                python: CPython 3.10.19
                root: /data_hss/zhanghaoran/CosyVoice/examples/qinche/cosyvoice2
                startedAt: "2026-03-05T04:18:07.265264Z"
                writerId: f029t7d1hxv6dwydcbw21l32d1upjvb8
        m: []
        python_version: 3.10.19
        t:
            "1":
                - 1
                - 5
                - 11
                - 49
                - 53
                - 105
            "2":
                - 1
                - 5
                - 11
                - 49
                - 50
                - 53
                - 83
                - 105
                - 106
            "3":
                - 2
                - 5
                - 13
                - 14
                - 16
                - 62
            "4": 3.10.19
            "5": 0.25.0
            "6": 4.51.3
            "12": 0.25.0
            "13": linux-x86_64
checkpoint:
    value: ../../../pretrained_models/CosyVoice2-0.5B/llm.pt
config:
    value: conf/cosyvoice2_llm.yaml
cv_data:
    value: dev.data.list
deepscale:
    value: false
deepscale_config:
    value: null
deepspeed:
    value: false
deepspeed_config:
    value: null
dist_backend:
    value: nccl
dpo:
    value: false
flow_checkpoint:
    value: null
llm_checkpoint:
    value: exp/cosyvoice2/llm_lr1e-6_batch8000/epoch_9_whole.pt
model:
    value: llm
model_dir:
    value: ../../../pretrained_models/CosyVoice2-0.5B
num_test_texts:
    value: 4
num_workers:
    value: 2
onnx_path:
    value: ../../../pretrained_models/CosyVoice2-0.5B
pin_memory:
    value: true
prefetch:
    value: 100
prompt_audio:
    value: ../../../data/qinche/inference_ref/prompt_1.wav
qwen_pretrain_path:
    value: ../../../pretrained_models/CosyVoice2-0.5B/CosyVoice-BlankEN
ref_model:
    value: null
save_states:
    value: model_only
stream:
    value: false
tensorboard_dir:
    value: tensorboard/cosyvoice2/llm_lr1e-6_batch8000
timeout:
    value: 60
train_data:
    value: train.data.list
train_engine:
    value: torch_ddp
use_amp:
    value: true
